package com.pat.crewhive.authuser;

import com.pat.crewhive.company.Company;
import com.pat.crewhive.manager.Role;
import com.pat.crewhive.manager.RoleService;
import com.pat.crewhive.manager.UserRole;
import com.pat.crewhive.security.JwtService;
import com.pat.crewhive.security.TokenBlackListService;
import com.pat.crewhive.security.exception.custom.ResourceAlreadyExistsException;
import com.pat.crewhive.common.PasswordUtil;
import com.pat.crewhive.common.StringUtils;
import com.pat.crewhive.user.User;
import com.pat.crewhive.user.UserRepository;
import com.pat.crewhive.user.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.LocalDate;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link AuthService}.
 * <p>
 * AuthService is not instantiated by Spring here: every collaborator is a Mockito mock,
 * wired together by hand in the constructor. This keeps the test fast (no ApplicationContext)
 * and isolates AuthService's own logic from the correctness of its dependencies, which get
 * their own dedicated tests instead.
 */
@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    @Mock
    private UserService userService;
    @Mock
    private UserRepository userRepository;
    @Mock
    private JwtService jwtService;
    @Mock
    private RefreshTokenService refreshTokenService;
    @Mock
    private RoleService roleService;
    @Mock
    private PasswordUtil passwordUtil;
    @Mock
    private EmailUtil emailUtil;
    @Mock
    private StringUtils stringUtils;
    @Mock
    private TokenBlackListService tokenBlackListService;

    // Built by hand instead of @InjectMocks: with 8 collaborators the automatic
    // field/constructor injection Mockito does is harder to follow than just calling
    // the real constructor, and this guarantees the wiring matches production exactly.
    //
    // This has to happen in @BeforeEach, not as a field initializer: JUnit builds the
    // test instance (running field initializers) BEFORE MockitoExtension injects the
    // @Mock fields, so at field-initializer time every mock above would still be null.
    private AuthService authService;

    private static final UUID USER_ID = UUID.randomUUID();
    private static final UUID COMPANY_ID = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        authService = new AuthService(
                userService, jwtService, refreshTokenService, userRepository,
                roleService, passwordUtil, emailUtil, stringUtils, tokenBlackListService
        );
    }

    private User buildUser(UUID userId, String email, String encodedPassword, Company company) {
        User user = new User(email, "Mario", "Rossi", encodedPassword);
        // userId is @Id with no Lombok setter (auto-generated by the DB), so the only
        // way to give a detached test entity an id is to poke the field via reflection.
        ReflectionTestUtils.setField(user, "userId", userId);
        user.setCompany(company);

        Role role = new Role("ROLE_USER", null);
        user.setRole(new UserRole(user, role));
        return user;
    }

    // ---------------------------------------------------------------------
    // login()
    // ---------------------------------------------------------------------

    @Test
    void login_returnsTokens_whenCredentialsAreValid() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);
        RefreshToken existingToken = new RefreshToken(UUID.randomUUID(), "old-token", user, LocalDate.now().plusDays(1));

        when(stringUtils.normalizeString("mario.rossi@example.com")).thenReturn("mario.rossi@example.com");
        when(userService.getUserByEmail("mario.rossi@example.com")).thenReturn(user);
        when(passwordUtil.NotMatches("P@ssw0rd!", "encoded-pwd")).thenReturn(false);
        when(refreshTokenService.getRefreshTokenByUser(user)).thenReturn(existingToken);
        when(jwtService.generateToken(USER_ID, "mario.rossi@example.com", "Mario", "Rossi", "ROLE_USER", null))
                .thenReturn("access-jwt");
        when(refreshTokenService.generateRefreshToken(user)).thenReturn("new-refresh-token");

        AuthResponseDTO result = authService.login(request);

        assertThat(result.getAccessToken()).isEqualTo("access-jwt");
        assertThat(result.getRefreshToken()).isEqualTo("new-refresh-token");
        // the pre-existing session must be invalidated before a new one is issued
        verify(refreshTokenService).invalidateRefreshToken(existingToken);
    }

    @Test
    void login_doesNotInvalidateAnyToken_whenUserHasNoExistingSession() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userService.getUserByEmail(anyString())).thenReturn(user);
        when(passwordUtil.NotMatches(anyString(), anyString())).thenReturn(false);
        when(refreshTokenService.getRefreshTokenByUser(user)).thenReturn(null);
        when(jwtService.generateToken(any(), anyString(), anyString(), anyString(), anyString(), any()))
                .thenReturn("access-jwt");
        when(refreshTokenService.generateRefreshToken(user)).thenReturn("new-refresh-token");

        authService.login(request);

        verify(refreshTokenService, never()).invalidateRefreshToken(any());
    }

    @Test
    void login_passesCompanyId_whenUserBelongsToACompany() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");
        Company company = new Company();
        ReflectionTestUtils.setField(company, "companyId", COMPANY_ID); // companyId has no setter either
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", company);

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userService.getUserByEmail(anyString())).thenReturn(user);
        when(passwordUtil.NotMatches(anyString(), anyString())).thenReturn(false);
        when(refreshTokenService.getRefreshTokenByUser(user)).thenReturn(null);
        when(refreshTokenService.generateRefreshToken(user)).thenReturn("new-refresh-token");

        authService.login(request);

        // ArgumentCaptor lets us inspect exactly what AuthService handed to a mock,
        // which is handy when you only care about one of several arguments.
        ArgumentCaptor<UUID> companyIdCaptor = ArgumentCaptor.forClass(UUID.class);
        verify(jwtService).generateToken(eq(USER_ID), anyString(), anyString(), anyString(), anyString(), companyIdCaptor.capture());
        assertThat(companyIdCaptor.getValue()).isEqualTo(COMPANY_ID);
    }

    @Test
    void login_throwsBadCredentialsException_whenPasswordDoesNotMatch() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "wrong-password");
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userService.getUserByEmail(anyString())).thenReturn(user);
        when(passwordUtil.NotMatches("wrong-password", "encoded-pwd")).thenReturn(true);

        assertThatThrownBy(() -> authService.login(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Invalid credentials");

        // fail fast: nothing token-related should happen once the password check fails
        verifyNoInteractions(refreshTokenService, jwtService);
    }

    // ---------------------------------------------------------------------
    // register()
    // ---------------------------------------------------------------------

    @Test
    void register_savesNewUser_withEncodedPasswordAndDefaultRole() {
        RegistrationDTO request = new RegistrationDTO("New.User@Example.com", "New", "User", "StrongP@ss1");
        Role globalUserRole = new Role("ROLE_USER", null);

        when(stringUtils.normalizeString("New.User@Example.com")).thenReturn("new.user@example.com");
        when(emailUtil.isValidEmail("new.user@example.com")).thenReturn(true);
        when(userRepository.existsByEmail("new.user@example.com")).thenReturn(false);
        when(passwordUtil.isStrong("StrongP@ss1")).thenReturn(true);
        when(passwordUtil.encodePassword("StrongP@ss1")).thenReturn("encoded-pwd");
        when(roleService.getOrCreateGlobalRoleUser()).thenReturn(globalUserRole);

        authService.register(request);

        ArgumentCaptor<User> savedUserCaptor = ArgumentCaptor.forClass(User.class);
        verify(userRepository).save(savedUserCaptor.capture());

        User savedUser = savedUserCaptor.getValue();
        assertThat(savedUser.getEmail()).isEqualTo("new.user@example.com");
        assertThat(savedUser.getPassword()).isEqualTo("encoded-pwd");
        assertThat(savedUser.getRole()).isNotNull();
        assertThat(savedUser.getRole().getRole()).isEqualTo(globalUserRole);
    }

    @Test
    void register_throwsBadCredentialsException_whenEmailFormatIsInvalid() {
        RegistrationDTO request = new RegistrationDTO("not-an-email", "New", "User", "StrongP@ss1");

        when(stringUtils.normalizeString("not-an-email")).thenReturn("not-an-email");
        when(emailUtil.isValidEmail("not-an-email")).thenReturn(false);

        assertThatThrownBy(() -> authService.register(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Invalid email format");

        verifyNoInteractions(userRepository, passwordUtil, roleService);
    }

    @Test
    void register_throwsResourceAlreadyExistsException_whenEmailIsTaken() {
        RegistrationDTO request = new RegistrationDTO("taken@example.com", "New", "User", "StrongP@ss1");

        when(stringUtils.normalizeString("taken@example.com")).thenReturn("taken@example.com");
        when(emailUtil.isValidEmail("taken@example.com")).thenReturn(true);
        when(userRepository.existsByEmail("taken@example.com")).thenReturn(true);

        assertThatThrownBy(() -> authService.register(request))
                .isInstanceOf(ResourceAlreadyExistsException.class)
                .hasMessage("Email already registered");

        verify(passwordUtil, never()).isStrong(anyString());
        verify(userRepository, never()).save(any());
    }

    @Test
    void register_throwsBadCredentialsException_whenPasswordIsWeak() {
        RegistrationDTO request = new RegistrationDTO("new.user@example.com", "New", "User", "weak");

        when(stringUtils.normalizeString("new.user@example.com")).thenReturn("new.user@example.com");
        when(emailUtil.isValidEmail("new.user@example.com")).thenReturn(true);
        when(userRepository.existsByEmail("new.user@example.com")).thenReturn(false);
        when(passwordUtil.isStrong("weak")).thenReturn(false);

        assertThatThrownBy(() -> authService.register(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Weak password provided");

        verify(userRepository, never()).save(any());
    }
}
