package com.pat.crewhive.authuser;

import com.pat.crewhive.company.Company;
import com.pat.crewhive.manager.Role;
import com.pat.crewhive.manager.RoleService;
import com.pat.crewhive.manager.UserRole;
import com.pat.crewhive.security.JwtService;
import com.pat.crewhive.security.TokenBlackListService;
import com.pat.crewhive.security.exception.custom.InvalidTokenException;
import com.pat.crewhive.security.exception.custom.ResourceAlreadyExistsException;
import com.pat.crewhive.security.exception.custom.ResourceNotFoundException;
import com.pat.crewhive.common.PasswordUtil;
import com.pat.crewhive.common.StringUtils;
import com.pat.crewhive.user.LogoutDTO;
import com.pat.crewhive.user.User;
import com.pat.crewhive.user.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.Instant;
import java.util.*;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link AuthService}.
 * <p>
 * AuthService is not instantiated by Spring here: every collaborator is a Mockito mock,
 * wired together by hand in the constructor. This keeps the test fast (no ApplicationContext)
 * and isolates AuthService's own logic from the correctness of its dependencies, which get
 * their own dedicated tests instead.
 */
@ExtendWith(MockitoExtension.class)
class AuthServiceTest {

    @Mock
    private UserRepository userRepository;
    @Mock
    private JwtService jwtService;
    @Mock
    private RefreshTokenService refreshTokenService;
    @Mock
    private RoleService roleService;
    @Mock
    private PasswordUtil passwordUtil;
    @Mock
    private EmailUtil emailUtil;
    @Mock
    private StringUtils stringUtils;
    @Mock
    private TokenBlackListService tokenBlackListService;

    // Built by hand instead of @InjectMocks: with 8 collaborators the automatic
    // field/constructor injection Mockito does is harder to follow than just calling
    // the real constructor, and this guarantees the wiring matches production exactly.
    //
    // This has to happen in @BeforeEach, not as a field initializer: JUnit builds the
    // test instance (running field initializers) BEFORE MockitoExtension injects the
    // @Mock fields, so at field-initializer time every mock above would still be null.
    private AuthService authService;

    private static final UUID USER_ID = UUID.randomUUID();
    private static final UUID COMPANY_ID = UUID.randomUUID();

    @BeforeEach
    void setUp() {
        authService = new AuthService(
                jwtService, refreshTokenService, userRepository,
                roleService, passwordUtil, emailUtil, stringUtils, tokenBlackListService
        );
    }

    private User buildUser(UUID userId, String email, String encodedPassword, Company company) {
        User user = new User(email, "Mario", "Rossi", encodedPassword);
        // userId is @Id with no Lombok setter (auto-generated by the DB), so the only
        // way to give a detached test entity an id is to poke the field via reflection.
        ReflectionTestUtils.setField(user, "userId", userId);
        user.setCompany(company);

        Role role = new Role("ROLE_USER", null);
        user.addRole(role);
        return user;
    }

    // ---------------------------------------------------------------------
    // login()
    // ---------------------------------------------------------------------

    @Test
    void login_returnsTokens_whenCredentialsAreValid() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);
        Set<String> roles = new HashSet<>();
        roles.add("ROLE_USER");

        when(stringUtils.normalizeString("mario.rossi@example.com")).thenReturn("mario.rossi@example.com");
        when(userRepository.findByEmail("mario.rossi@example.com")).thenReturn(Optional.of(user));
        when(passwordUtil.NotMatches("P@ssw0rd!", "encoded-pwd")).thenReturn(false);
        when(jwtService.generateToken(USER_ID, "mario.rossi@example.com", "Mario", "Rossi", roles, null))
                .thenReturn("access-jwt");
        when(refreshTokenService.issueNewFamily(user)).thenReturn("new-refresh-token");

        AuthResponseDTO result = authService.login(request);

        assertThat(result.accessToken()).isEqualTo("access-jwt");
        assertThat(result.refreshToken()).isEqualTo("new-refresh-token");
        // issueNewFamily replaces the previous session by itself
        verify(refreshTokenService).issueNewFamily(user);
    }

    @Test
    void login_passesCompanyId_whenUserBelongsToACompany() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");
        Company company = new Company();
        ReflectionTestUtils.setField(company, "companyId", COMPANY_ID); // companyId has no setter either
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", company);

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userRepository.findByEmail(anyString())).thenReturn(Optional.of(user));
        when(passwordUtil.NotMatches(anyString(), anyString())).thenReturn(false);
        when(refreshTokenService.issueNewFamily(user)).thenReturn("new-refresh-token");

        authService.login(request);

        // ArgumentCaptor lets us inspect exactly what AuthService handed to a mock,
        // which is handy when you only care about one of several arguments.
        ArgumentCaptor<UUID> companyIdCaptor = ArgumentCaptor.forClass(UUID.class);
        verify(jwtService).generateToken(eq(USER_ID), anyString(), anyString(), anyString(), any(), companyIdCaptor.capture());
        assertThat(companyIdCaptor.getValue()).isEqualTo(COMPANY_ID);
    }

    @Test
    void login_dropsLegacyGlobalManagerRole_fromToken() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");
        Company company = new Company();
        ReflectionTestUtils.setField(company, "companyId", COMPANY_ID);
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", company);
        user.addRole(new Role("ROLE_MANAGER", null)); // vecchio ruolo globale

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userRepository.findByEmail(anyString())).thenReturn(Optional.of(user));
        when(passwordUtil.NotMatches(anyString(), anyString())).thenReturn(false);
        when(refreshTokenService.issueNewFamily(user)).thenReturn("new-refresh-token");

        authService.login(request);

        ArgumentCaptor<Set<String>> rolesCaptor = ArgumentCaptor.forClass(Set.class);
        verify(jwtService).generateToken(eq(USER_ID), anyString(), anyString(), anyString(), rolesCaptor.capture(), eq(COMPANY_ID));
        assertThat(rolesCaptor.getValue()).containsExactly("ROLE_USER");
    }

    @Test
    void login_throwsBadCredentialsException_whenPasswordDoesNotMatch() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "wrong-password");
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userRepository.findByEmail(anyString())).thenReturn(Optional.of(user));
        when(passwordUtil.NotMatches("wrong-password", "encoded-pwd")).thenReturn(true);

        assertThatThrownBy(() -> authService.login(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Invalid credentials");

        // fail fast: nothing token-related should happen once the password check fails
        verifyNoInteractions(refreshTokenService, jwtService);
    }

    @Test
    void login_throwsAccountDisabled_whenUserIsDeactivated() {
        AuthRequestDTO request = new AuthRequestDTO("mario.rossi@example.com", "P@ssw0rd!");

        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");
        when(userRepository.findByEmail("mario.rossi@example.com")).thenReturn(Optional.empty());
        when(userRepository.existsInactiveByEmail("mario.rossi@example.com")).thenReturn(true);

        assertThatThrownBy(() -> authService.login(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Account disabled");

        verifyNoInteractions(refreshTokenService, jwtService);
    }

    @Test
    void login_throwsUserNotFound_whenEmailDoesNotExistAtAll() {
        AuthRequestDTO request = new AuthRequestDTO("nobody@example.com", "P@ssw0rd!");

        when(stringUtils.normalizeString(anyString())).thenReturn("nobody@example.com");
        when(userRepository.findByEmail("nobody@example.com")).thenReturn(Optional.empty());
        when(userRepository.existsInactiveByEmail("nobody@example.com")).thenReturn(false);

        assertThatThrownBy(() -> authService.login(request))
                .isInstanceOf(ResourceNotFoundException.class);

        verifyNoInteractions(refreshTokenService, jwtService);
    }

    // ---------------------------------------------------------------------
    // register()
    // ---------------------------------------------------------------------

    @Test
    void register_savesNewUser_withEncodedPasswordAndDefaultRole() {
        RegistrationDTO request = new RegistrationDTO("New.User@Example.com", "New", "User", "StrongP@ss1");
        Role globalUserRole = new Role("ROLE_USER", null);

        when(stringUtils.normalizeString("New.User@Example.com")).thenReturn("new.user@example.com");
        when(emailUtil.isValidEmail("new.user@example.com")).thenReturn(true);
        when(userRepository.existsByEmail("new.user@example.com")).thenReturn(false);
        when(passwordUtil.isStrong("StrongP@ss1")).thenReturn(true);
        when(passwordUtil.encodePassword("StrongP@ss1")).thenReturn("encoded-pwd");
        when(roleService.getOrCreateGlobalRoleUser()).thenReturn(globalUserRole);

        authService.register(request);

        ArgumentCaptor<User> savedUserCaptor = ArgumentCaptor.forClass(User.class);
        verify(userRepository).save(savedUserCaptor.capture());

        User savedUser = savedUserCaptor.getValue();
        assertThat(savedUser.getEmail()).isEqualTo("new.user@example.com");
        assertThat(savedUser.getPassword()).isEqualTo("encoded-pwd");
        assertThat(savedUser.getRoles()).isNotNull();
        assertThat(savedUser.getRoles().stream().filter(r -> r.getRole().equals(globalUserRole)).toList().getFirst().getRole()).isEqualTo(globalUserRole);
    }

    @Test
    void register_throwsBadCredentialsException_whenEmailFormatIsInvalid() {
        RegistrationDTO request = new RegistrationDTO("not-an-email", "New", "User", "StrongP@ss1");

        when(stringUtils.normalizeString("not-an-email")).thenReturn("not-an-email");
        when(emailUtil.isValidEmail("not-an-email")).thenReturn(false);

        assertThatThrownBy(() -> authService.register(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Invalid email format");

        verifyNoInteractions(userRepository, passwordUtil, roleService);
    }

    @Test
    void register_throwsResourceAlreadyExistsException_whenEmailIsTaken() {
        RegistrationDTO request = new RegistrationDTO("taken@example.com", "New", "User", "StrongP@ss1");

        when(stringUtils.normalizeString("taken@example.com")).thenReturn("taken@example.com");
        when(emailUtil.isValidEmail("taken@example.com")).thenReturn(true);
        when(userRepository.existsByEmail("taken@example.com")).thenReturn(true);

        assertThatThrownBy(() -> authService.register(request))
                .isInstanceOf(ResourceAlreadyExistsException.class)
                .hasMessage("Email already registered");

        verify(passwordUtil, never()).isStrong(anyString());
        verify(userRepository, never()).save(any());
    }

    @Test
    void register_throwsBadCredentialsException_whenPasswordIsWeak() {
        RegistrationDTO request = new RegistrationDTO("new.user@example.com", "New", "User", "weak");

        when(stringUtils.normalizeString("new.user@example.com")).thenReturn("new.user@example.com");
        when(emailUtil.isValidEmail("new.user@example.com")).thenReturn(true);
        when(userRepository.existsByEmail("new.user@example.com")).thenReturn(false);
        when(passwordUtil.isStrong("weak")).thenReturn(false);

        assertThatThrownBy(() -> authService.register(request))
                .isInstanceOf(BadCredentialsException.class)
                .hasMessage("Weak password provided");

        verify(userRepository, never()).save(any());
    }

    // ---------------------------------------------------------------------
    // rotate_token()
    // ---------------------------------------------------------------------

    @Test
    void rotate_token_returnsNewAccessAndRefreshToken_whenRotationSucceeds() {
        String raw = UUID.randomUUID().toString();
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);
        Set<String> roles = Set.of("ROLE_USER");

        when(refreshTokenService.rotate(raw)).thenReturn(new RefreshTokenService.Rotation(user, "new-refresh-token"));
        when(stringUtils.normalizeString("mario.rossi@example.com")).thenReturn("mario.rossi@example.com");
        when(jwtService.generateToken(USER_ID, "mario.rossi@example.com", "Mario", "Rossi", roles, null))
                .thenReturn("access-jwt");

        AuthResponseDTO result = authService.rotate_token(raw);

        assertThat(result.accessToken()).isEqualTo("access-jwt");
        assertThat(result.refreshToken()).isEqualTo("new-refresh-token");
    }

    @Test
    void rotate_token_passesCompanyId_whenUserBelongsToACompany() {
        String raw = UUID.randomUUID().toString();
        Company company = new Company();
        ReflectionTestUtils.setField(company, "companyId", COMPANY_ID);
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", company);

        when(refreshTokenService.rotate(raw)).thenReturn(new RefreshTokenService.Rotation(user, "new-refresh-token"));
        when(stringUtils.normalizeString(anyString())).thenReturn("mario.rossi@example.com");

        authService.rotate_token(raw);

        verify(jwtService).generateToken(eq(USER_ID), anyString(), anyString(), anyString(), any(), eq(COMPANY_ID));
    }

    @Test
    void rotate_token_propagatesInvalidToken_andIssuesNoAccessToken() {
        String raw = UUID.randomUUID().toString();

        when(refreshTokenService.rotate(raw)).thenThrow(new InvalidTokenException("Invalid refresh token"));

        assertThatThrownBy(() -> authService.rotate_token(raw)).isInstanceOf(InvalidTokenException.class);

        verifyNoInteractions(jwtService);
    }

    @Test
    void rotate_token_rejectsBlankOrNonUuidTokens_withoutTouchingTheDatabase() {
        assertThatThrownBy(() -> authService.rotate_token(null)).isInstanceOf(InvalidTokenException.class);
        assertThatThrownBy(() -> authService.rotate_token(" ")).isInstanceOf(InvalidTokenException.class);
        assertThatThrownBy(() -> authService.rotate_token("not-a-uuid")).isInstanceOf(InvalidTokenException.class);

        verifyNoInteractions(refreshTokenService, jwtService);
    }

    // ---------------------------------------------------------------------
    // logout()
    // ---------------------------------------------------------------------

    @Test
    void logout_revokesFamilyAndBlacklistsAccessToken_whenTokenBelongsToUser() {
        User user = buildUser(USER_ID, "mario.rossi@example.com", "encoded-pwd", null);
        RefreshToken rt = new RefreshToken(UUID.randomUUID(), "hash", UUID.randomUUID(), user, Instant.now().plusSeconds(60), null);
        Date exp = new Date();

        when(refreshTokenService.getValidToken("raw")).thenReturn(rt);

        authService.logout(new LogoutDTO(USER_ID, "raw"), "jti-1", exp);

        verify(refreshTokenService).revokeFamily(rt);
        verify(tokenBlackListService).revoke("jti-1", exp);
    }

    @Test
    void logout_throwsInvalidToken_whenTokenBelongsToAnotherUser() {
        User owner = buildUser(UUID.randomUUID(), "other@example.com", "encoded-pwd", null);
        RefreshToken rt = new RefreshToken(UUID.randomUUID(), "hash", UUID.randomUUID(), owner, Instant.now().plusSeconds(60), null);

        when(refreshTokenService.getValidToken("raw")).thenReturn(rt);

        assertThatThrownBy(() -> authService.logout(new LogoutDTO(USER_ID, "raw"), "jti-1", new Date()))
                .isInstanceOf(InvalidTokenException.class)
                .hasMessage("Refresh Token does not belong to user");

        verify(refreshTokenService, never()).revokeFamily(any());
        verifyNoInteractions(tokenBlackListService);
    }

    @Test
    void logout_throwsInvalidToken_whenTokenIsUnknownOrExpired() {
        when(refreshTokenService.getValidToken("raw")).thenThrow(new InvalidTokenException("Refresh Token expired or missing"));

        assertThatThrownBy(() -> authService.logout(new LogoutDTO(USER_ID, "raw"), "jti-1", new Date()))
                .isInstanceOf(InvalidTokenException.class);

        verifyNoInteractions(tokenBlackListService);
    }

    @Test
    void logout_throwsInvalidToken_whenRefreshTokenIsBlank() {
        assertThatThrownBy(() -> authService.logout(new LogoutDTO(USER_ID, " "), "jti-1", new Date()))
                .isInstanceOf(InvalidTokenException.class);

        verifyNoInteractions(refreshTokenService, tokenBlackListService);
    }
}
