version: "3.9"

services:
  app:
    build: .
    image: crewhive-testing
    ports:
      - "0.0.0.0:8080:8080"
    container_name: crewhive
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_POOL_MAX: 16
      DB_POOL_MIN: 2
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: crewhive-db
    environment:
      POSTGRES_DB: crewdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
