spring:
  application:
    name: hours-calculator-test

  datasource:
    url: jdbc:postgresql://localhost:5432/hours-calculator-test
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # consigliato nei test per DB pulito ad ogni run
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
